name: "diff-upgrade"
version: "0.1.1"
usage: "Upgrade helm releases with a preview diff"
description: "Upgrade helm releases with a preview diff"
useTunnel: true
command: "bash $HELM_PLUGIN_DIR/bin/diff-upgrade.sh"
hooks:
  install: "cd $HELM_PLUGIN_DIR; bash install-binary.sh"
  update: "cd $HELM_PLUGIN_DIR; bash install-binary.sh"
